[package]
name = "cfn"
version = "0.1.0"
authors = ["Sam Rijs <srijs@airpost.net>"]

[dependencies]
indexmap = { version = "1.0", features = ["serde-1"] }
serde = "1.0"
serde_derive = "1.0"
serde_json = "1.0"
